begin;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions;
select no_plan();
truncate cms_page_route_events,cms_page_routes,cms_new_page_identity,page_revision_blocks,promotion_revision_media,cms_promotion_identity,media_audit_events,revision_media_refs,media_versions,media_assets,content_publication_events,content_publication_state,content_revisions,content_documents;
select cms_import_shared_media();
create temporary table shared_fixture(k text primary key,doc uuid,p jsonb,baseline uuid,draft uuid,restored uuid);
insert into shared_fixture(k,doc,p)
select k,cms_shared_service_id(k),'{"schemaVersion":3,"publicTitle":"Baseline","h1":"Baseline heading","eyebrow":"Eyebrow","intro":"Intro","imageAlt":"Alt","signsTitle":"Signs","signsDescription":"Signs intro","processTitle":"Process","processDescription":"Process intro","benefitsDescription":"Benefits intro","resultDescription":"Result","seoTitle":"SEO","seoDescription":"Description","images":["76906e25-9adc-44a4-8ada-7851d1ba3b6c"],"signs":["Sign"],"process":["Step"],"benefits":["Benefit"],"faqs":[{"question":"Question","answer":"Answer"}],"relatedLinks":[{"label":"Sofa","href":"/sofa-cleaning"}],"beforeAfter":{"title":"Pair","description":"Same job","beforeImage":"76906e25-9adc-44a4-8ada-7851d1ba3b6c","afterImage":"c228e26c-817b-4c17-82eb-8d61ebba1040","beforeAlt":"Before","afterAlt":"After"}}'::jsonb
from unnest(array['sofa-cleaning','mattress-cleaning','carpet-cleaning','car-upholstery-cleaning','armchair-chair-cleaning','delicate-upholstery-cleaning']) k;
grant select,update on shared_fixture to authenticated,anon;
select ok(cms_valid_service_payload(k,p),k||' schema 3 accepted') from shared_fixture;
update shared_fixture set baseline=cms_import_shared_baseline(k,p);
select is(cms_import_shared_baseline(k,p),baseline,k||' baseline idempotent') from shared_fixture;
select is((select count(*)::int from content_documents),6,'exactly six shared documents');
select is((select count(*)::int from media_versions),20,'exactly twenty logical static versions; no copies');
select is(cms_import_shared_media(),20,'media import idempotent');
select is((select count(*)::int from media_versions),20,'media count unchanged');
select is((select count(*)::int from media_audit_events),20,'system baseline authorship only');
select is((select count(*)::int from content_revisions where created_by is not null),0,'baseline is not attributed to invented admin');
select is((select count(*)::int from revision_media_refs where revision_id=f.baseline),5,f.k||' exact roles including before/after') from shared_fixture f;
select throws_ok($$insert into content_documents(content_type,content_key) values('page','sofa-cleaning')$$,'23514',null,'AAL2 does not broaden document types');
select throws_ok($$insert into content_documents(content_type,content_key) values('service','unregistered-cleaning')$$,'23514',null,'unregistered service not allowed');
select ok(not cms_valid_service_payload(k,p||'{"crmServiceName":"other"}'),k||' CRM cannot be edited') from shared_fixture;
select ok(not cms_valid_service_payload(k,p||'{"imagePosition":"fixed"}'),k||' arbitrary CSS rejected') from shared_fixture;
select ok(not cms_valid_service_payload(k,p||'{"beforeAfter":null}'),k||' malformed pair rejected') from shared_fixture;
select ok(not cms_valid_service_payload(k,p||'{"relatedLinks":[{"label":"bad","href":"javascript:alert(1)"}]}'),k||' unsafe URL rejected') from shared_fixture;
select ok(not cms_valid_service_payload(k,p||'{"intro":"<script>"}'),k||' HTML rejected') from shared_fixture;

select ok(not cms_valid_service_payload(k,p||'{"relatedLinks":[{"label":"AC","href":"/air-conditioner-cleaning"}]}'),k||' shared related-link scope unchanged') from shared_fixture;

insert into auth.users(id,invited_at) values
('50000000-0000-4000-8000-000000000001',null),('50000000-0000-4000-8000-000000000002',null),
('50000000-0000-4000-8000-000000000003',null),('50000000-0000-4000-8000-000000000004',now());
insert into cms_admin_members(user_id,is_active) values
('50000000-0000-4000-8000-000000000001',true),('50000000-0000-4000-8000-000000000003',false),('50000000-0000-4000-8000-000000000004',true);
set local role anon;
select throws_ok($$select * from content_revisions$$,'42501',null,'anon cannot read drafts/history');
select throws_ok($$select * from media_assets$$,'42501',null,'anon cannot manage media');
select throws_ok(format('select cms_read_service_editor(%L)',k),'42501',null,k||' anonymous editor denied') from shared_fixture;
select is(cms_read_published_service(k)->'payload',p,k||' anon projection is published only') from shared_fixture;
select is(cms_read_published_service('window-cleaning'),null::jsonb,'unmanaged public projection fails closed');
reset role;
set local role authenticated;
select set_config('request.jwt.claims','{"sub":"50000000-0000-4000-8000-000000000002","aal":"aal2","role":"authenticated"}',true);
select is((select count(*)::int from content_revisions),0,'nonmember RLS hides all shared revisions');
select throws_ok(format('select cms_read_service_editor(%L)',k),'42501',null,k||' nonmember denied') from shared_fixture;
select set_config('request.jwt.claims','{"sub":"50000000-0000-4000-8000-000000000003","aal":"aal2","role":"authenticated"}',true);
select is((select count(*)::int from media_versions),0,'inactive cannot read media');
select throws_ok(format('select cms_save_managed_draft(%L,1,%L,%L::jsonb)',k,baseline,p),'42501',null,k||' inactive denied') from shared_fixture;
select set_config('request.jwt.claims','{"sub":"50000000-0000-4000-8000-000000000001","aal":"aal1","role":"authenticated"}',true);
select is((select count(*)::int from content_revisions),0,'AAL1 RLS hides every revision');
select throws_ok(format('select cms_read_service_editor(%L)',k),'42501',null,k||' AAL1 editor denied') from shared_fixture;
select throws_ok(format('select cms_publish_managed_revision(%L,1,%L)',k,baseline),'42501',null,k||' AAL1 publish denied') from shared_fixture;
select set_config('request.jwt.claims','{"sub":"50000000-0000-4000-8000-000000000004","aal":"aal2","role":"authenticated"}',true);
select throws_ok(format('select cms_read_service_editor(%L)',k),'42501',null,k||' pending onboarding denied') from shared_fixture;
select set_config('request.jwt.claims','{"sub":"50000000-0000-4000-8000-000000000001","aal":"aal2","role":"authenticated"}',true);
select is((select count(*)::int from content_revisions),6,'active AAL2 can read all intended shared services');
select throws_ok($$select cms_import_shared_media()$$,'42501',null,'admin cannot bootstrap/invent assets');
select throws_ok($$select cms_import_shared_baseline('sofa-cleaning',null)$$,'42501',null,'admin cannot bootstrap/invent documents');
select throws_ok($$insert into content_documents(content_type,content_key) values('service','arbitrary')$$,'42501',null,'admin cannot create routes');
select throws_ok(format('select cms_save_managed_draft(%L,1,%L,%L::jsonb)',k,baseline,p||'{"images":["f0000000-0000-4000-8000-000000000099"]}'),'23503',null,k||' forged media version denied') from shared_fixture;
select throws_ok(format('select cms_save_managed_draft(%L,1,%L,%L::jsonb)',k,(select baseline from shared_fixture where k<>f.k limit 1),p),'PT409',null,k||' cross-document base rejected') from shared_fixture f;
-- A saves: B's untouched generation still remains valid.
update shared_fixture set draft=cms_save_managed_draft(k,1,baseline,p||jsonb_build_object('h1','Draft '||k)) where k='sofa-cleaning';
select is((select generation::int from content_publication_state where document_id=f.doc),1,k||' unaffected by sofa save') from shared_fixture f where k<>'sofa-cleaning';
update shared_fixture set draft=cms_save_managed_draft(k,1,baseline,p||jsonb_build_object('h1','Draft '||k)) where k<>'sofa-cleaning';
select is(cms_read_published_service(k)->'payload',p,k||' draft never leaks into public payload/SEO') from shared_fixture;
select throws_ok(format('select cms_save_managed_draft(%L,1,%L,%L::jsonb)',k,baseline,p),'PT409',null,k||' stale editor conflict, no silent overwrite') from shared_fixture;
select throws_ok(format('select cms_save_managed_draft(%L,2,%L,null,%L)',k,draft,(select baseline from shared_fixture where k<>f.k limit 1)),'22023',null,k||' cross-document restore denied') from shared_fixture f;
select is(cms_publish_managed_revision(k,2,draft),draft,k||' publishes exact saved revision') from shared_fixture;
select is(cms_read_published_service(k)->'payload'->>'h1','Draft '||k,k||' independently published correct service') from shared_fixture;
update shared_fixture set restored=cms_save_managed_draft(k,3,draft,null,baseline);
select is(cms_read_published_service(k)->'payload'->>'h1','Draft '||k,k||' restore creates draft without publishing') from shared_fixture;
select is((select jsonb_agg(to_jsonb(r)-'revision_id' order by usage_role,position) from revision_media_refs r where revision_id=f.restored),(select jsonb_agg(to_jsonb(r)-'revision_id' order by usage_role,position) from revision_media_refs r where revision_id=f.baseline),k||' restore preserves exact historical refs/alt/caption') from shared_fixture f;
select is(cms_publish_managed_revision(k,4,restored),restored,k||' publishes rollback as new revision') from shared_fixture;
select is(cms_read_published_service(k)->'payload',p,k||' rollback restores complete original payload') from shared_fixture;
select is((select count(*)::int from content_revisions where document_id=f.doc),3,k||' independent revision numbering') from shared_fixture f;
select is((select count(*)::int from content_revisions where document_id=f.doc and created_by='50000000-0000-4000-8000-000000000001'),2,k||' real caller attribution for human drafts') from shared_fixture f;
select is((select count(*)::int from content_publication_events where document_id=f.doc and published_by='50000000-0000-4000-8000-000000000001'),2,k||' human publish attribution') from shared_fixture f;
select is(cms_read_service_editor(k)->>'publishedBy','50000000-0000-4000-8000-000000000001',k||' publisher matches current publication') from shared_fixture;
select is((select count(distinct u->>'serviceKey')::int from jsonb_array_elements(cms_media_detail('7828fc91-9bb4-48b5-84ae-045b3051fc5c')->'usages') u),6,'shared asset usages identify all six service routes');
reset role;
select is(cms_import_shared_baseline(k,p),baseline,k||' repeated bootstrap retains edited authoritative history') from shared_fixture;
select is((select count(*)::int from content_revisions),18,'bootstrap did not reset or duplicate histories');
select is((select count(*)::int from content_publication_state where generation=5),6,'bootstrap did not reset pointers/generations');
select throws_ok($$update content_revisions set h1='overwrite'$$,'55000',null,'history remains immutable');
select throws_ok($$delete from revision_media_refs$$,'55000',null,'historical media refs immutable');
select throws_ok($$delete from media_versions$$,'55000',null,'referenced versions cannot be deleted');
select is(jsonb_array_length(cms_read_public_media_version('76906e25-9adc-44a4-8ada-7851d1ba3b6c')->'serviceKeys'),6,'public media projection carries its actual published service owners');
select * from finish();
rollback;
